version: "3.9"
services:
  scmalgorithm_fe:
    container_name: scm_fe
    build:
      context: .
      dockerfile: ./fe/Dockerfile   
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true    
    volumes: ['./fe:/app']
   
  scmalgorithm_be:
    container_name: scm_be
    build:
      context: .
      dockerfile: ./be/Dockerfile
    volumes: ['./be:/code']
    ports:
      - "5000:5000"
 
  
